### ISSUE TITLE
Option to control bin size for geom_hex in oneVsAllPlot()

### ISSUE THREAD

**Issue by hrj21** [jtheorell/flowSpecs#1]
Hello! Thank you for creating this package. I have a minor feature request:

It would be nice to be able to specify the `bins` argument used by `geom_hex()`, inside the `oneVsAllPlot()` function. It might even be enough to add the `...` argument to `oneVsAllPlot()`, though I installed the package from Bioconductor and I don't seem to have the `oneVsAllPlotCoFunction()` that is called inside `oneVsAllPlot()`.

At the moment I achieve what I want by extracting the `$data` slot from the ggplot object:

```
p <- oneVsAllPlot(full_panel_trans, "AF647_IgM", saveResult = FALSE)

ggplot(p$data, aes(value, Y)) +
  facet_wrap(~ variable, scales = "free") +
  geom_hex(bins = 100)
```

Thanks again for the package!
Hefin

**Comment by jtheorell** [comment]
Dear Hefin, 
Thank you for your request! I will deal with this asap. Tried now, but it was slightly harder than it appeared on the surface. Please remind me if you think I am too slow. WIll report back otherwise as soon as there is an update in the devel version. 
Best
Jakob

**Comment by jtheorell** [comment]
Dear Hefin, 
Now I have added this, that clearly increases the versatility of the function. Thanks for the suggestion! Should get through to the development version at BioConductor in a few days, or you could take it straight from here. 
Best regards
Jakob

**Comment by hrj21** [comment]
Works like a charm! Thank you for implementing this ❤️
