### ISSUE TITLE
Missing fluorophore in spectral matrix

### ISSUE THREAD

**Issue by hrj21** [jtheorell/flowSpecs#2]
Hi! Thanks again for this package.

I came up against an issue today when trying to unmix from files that were not recorded explicitly as reference controls in Spectroflow. I have three unmixing controls on cells (attached in .zip):

- PerCP
- PerCP-Cy5.5
- Unstained

and a single "full stain" that was actually just the two reference controls concatenated in FlowJo. I attempt to unmix using the following script:

```
# Load packages -----------------------------------------------------------
library(flowSpecs)
library(flowCore)

# Load data ---------------------------------------------------------------
unmixCtrls <- read.flowSet(
  files = c("export_PerCP-Cy55.fcs", "export_PerCP.fcs", "export_Unstained.fcs"),
  truncate_max_range = FALSE
)

fullPanel <- read.flowSet(files = c("Full.fcs"), truncate_max_range = FALSE)

# Estimate unmixing matrix ------------------------------------------------
spec_mat <- specMatCalc(
  unmixCtrls, 
  groupNames = c("export_"), 
  autoFluoName = "export_Unstained.fcs"
)

rownames(spec_mat)
```

But instead of having a row per fluorophore plus autofluorescence, I get the rows "PerCP-Cy55", "Unstained", and "AutoFluo". The full-stained sample then looks very weird if I try to unmix with this matrix. This data unmixes ok in Spectroflow so I know they *can* be unmixed. I feel I'm doing something wrong where I haven't before and would really appreciate your guidance.

One thing I noticed in trying to troubleshoot is that it seems as though your `specMatCalc` function calls the function `specCalc`, but I can't find the latter in the package's namespace to query.

Many thanks for your help.
Hefin

**Comment by hrj21** [comment]
[fcs_files.zip](https://github.com/jtheorell/flowSpecs/files/9133074/fcs_files.zip)

**Comment by jtheorell** [comment]
Dear Hefin, 
Thank you for once again pointing to an important issue. In this case, it seems like it is is my slightly myopic lazyness that has led to this issue: I generally run bead controls, or dead cell marker controls that stain all the cells homogenuously. This means that it seems I have not included a step for selection of the positive population in the algorithm. Therefore, with your samples, the algorithm simply took the median value for each channel, and then the PerCP sample had the lowest sum of medians, and thence was identified as the negative control. After pre-filtering the positive population in the B6 (PerCP) and P8 (PerCPCy5.5), it work
s like a charm. I will of course fix this, but if you would like to run straight away, you can do that, or use the pre-gated controls included here. 
Best
Jakob
[Pos_selected_ctrls.zip](https://github.com/jtheorell/flowSpecs/files/9146536/Pos_selected_ctrls.zip)

**Comment by hrj21** [comment]
Oh of course! I'm sorry, my mind completely glossed over the gating of the positive population *eye roll*. This makes complete sense, I will just gate the positive peak manually. I suppose it would be nice if either the function could reliably gate the positive peak and/or the user could specify a range of values that define the positive (not to make more work for you). Thanks for your help!

Out of curiosity, where does the `specCalc` function come from in the `fsApply` call? I can't find it in the package.

```
function (unmixCtrls, groupNames, autoFluoName) 
{
    specCalcMat <- fsApply(unmixCtrls, specCalc)

...
```

**Comment by jtheorell** [comment]
Dear Hefin, 
Currently on holiday so a bit slow on the update side, but will get there eventually and will follow through with this. It should be very straight forward to just include a step for picking the highest of two peaks in the channel with the highest variance, so that will come eventually and I will keep the issue open until then. 
Now, when it comes to the function, it is an under-the-hood function of the flowSpecs package. You can access it by flowSpecs:::specCalc, which is true for all such functions. A very handy thing! 
All the best
Jakob

**Comment by jtheorell** [comment]
Hi again, 
Now I got some time to deal with this issue. A new version has been uploaded and should be available as devel any day if it passes the Bioconductor controls. I tested the new version and it worked with your files, so fingers crossed it does so for you too. Please get back when you have tested it. The function now takes both sampels with and without internal negative controls, but it still requires you to upload a separate universal negative, importantly. 
Best
Jakob
