### ISSUE TITLE
Spectral unmixing of Bigfoot data

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [jtheorell/flowSpecs#3]
Hi Jakob,

thanks a lot for this tool.

I'm figure out to unmix data from Bigfoot but I'm having some trouble with the calculation of spectral matrix.

The error is the follow:  Error in h(simpleError(msg, call)) 'exprs': missing value where TRUE/FALSE needed.

Attached you can find the flowSet.
[flowSet_Bigfoot.zip](https://github.com/jtheorell/flowSpecs/files/11019861/flowSet_Bigfoot.zip)

Best,

Domenico

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.utf8  LC_CTYPE=Italian_Italy.utf8    LC_MONETARY=Italian_Italy.utf8 LC_NUMERIC=C                   LC_TIME=Italian_Italy.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowCore_2.10.0  flowSpecs_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10         rstudioapi_0.14     magrittr_2.0.3      BiocGenerics_0.44.0 tidyselect_1.2.0    munsell_0.5.0       BiocParallel_1.32.5 lattice_0.20-45     colorspace_2.1-0    R6_2.5.1           
[11] rlang_1.1.0         fansi_1.0.4         stringr_1.5.0       plyr_1.8.8          dplyr_1.1.0         tools_4.2.2         parallel_4.2.2      grid_4.2.2          Biobase_2.58.0      gtable_0.3.1       
[21] utf8_1.2.3          cli_3.6.0           matrixStats_0.63.0  tibble_3.2.0        lifecycle_1.0.3     reshape2_1.4.4      cytolib_2.10.1      ggplot2_3.4.1       RProtoBufLib_2.10.0 vctrs_0.6.0        
[31] S4Vectors_0.36.2    codetools_0.2-18    glue_1.6.2          stringi_1.7.12      pillar_1.8.1        compiler_4.2.2      generics_0.1.3      scales_1.2.1        stats4_4.2.2        zoo_1.8-11

**Comment by jtheorell** [comment]
Dear Domenico, 
Thank you for reaching out, this can surely be sorted. Are you in stress, or could the answer take a few days? Will have considerably more time towards the end of next week to dig into this namely. 
Best regards
Jakob

**Comment by DomenicoSkyWalker89** [comment]
Dear Jakob,
Thank you for your quick answer. I have time to wait for sure. I can test other mAbs meanwhile.

I'm so excited to test flowSpecs!

All the best,

Domenico

**Comment by DomenicoSkyWalker89** [comment]
Dear Jakob,

I will do some experiments with the bigfoot next week, so I'm wondering if you sorted the problem with bigfoot files.

Best,

Domenico

**Comment by jtheorell** [comment]
Dear Domenico,
Thank you for your patience! I think I might have found it. Internally, the algorithm uses FSC.A and SSC.A to define the peak population that the intensities for the individual beads and cells are going to be calculated from. It seems like your file does not have any FSC and SSC values. I guess the bigfoot have them, right? If so, include them and try again. If it still does not work, please reach out again!
Best
J

**Comment by DomenicoSkyWalker89** [comment]
Dear Jakob,

I did the analysis with and without  FSC.A and SSC.A parameters but unfortunately I had the same issue. I share with you the unmixed files that I used. Any suggestion is welcome.

Thanks a lot for your precious help.

Best,

Domenico


[Unmixed_controls_Bigfoot_1.zip](https://github.com/jtheorell/flowSpecs/files/11159112/Unmixed_controls_Bigfoot_1.zip)

[Unmixed_controls_Bigfoot_2.zip](https://github.com/jtheorell/flowSpecs/files/11159117/Unmixed_controls_Bigfoot_2.zip)

**Comment by jtheorell** [comment]
Dear Domenico, 
I think I have sorted the issue now, please pull the latest version from here to try it out today and get back if it still does not do it for you. One question: these files are slightly unusual as it seems like they include the unmixed variables among the unmixed ones. For now, I have excluded all the varliables that included the name "comp". If this is wrong, please tell me, as they willl now be removed together with the sort variables, that strangely are also included as parameters in the exprs portion of the fcs files.

**Comment by jtheorell** [comment]
Minor thing: if you call the groups "Beads_" and "Dead_", you will not get the annoying "_" as the initial part of the row names.

**Comment by DomenicoSkyWalker89** [comment]
Dear Jakob,

The code seems to work now very well. I need more time to test it for the following 'Spectral unmixing' step of the fullstained samples. For sure I'm going to test it nest week.
About you question, you are right. The Bigfoot software include in the exported files both the unmixed variables among the unmixed ones. I'll figure out it with the specialist. Thanks a lot.

Best,

Domenico

**Comment by jtheorell** [comment]
Great to hear that it works! Please get back if you run into new issues; the bigfoot files are clearly quite different, so it would not surprise me if some more changes are needed.
